server: 
  port: 8081
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: system
    password: root
    driver-class-name: oracle.jdbc.driver.OracleDriver
  devtools: 
    livereload: 
      enabled: true
  thymeleaf:
    cache: false
mybatis:
  config: mybatis-config.xml
  type-aliases-package: com.item.demo.model
  mapper-locations: mybatis/mapper/*.xml

logging:
  level: 
    jdbc:
      sqlonly: info
      sqltiming: info
      resultsettable: info
      audit: info
      resultset: info
      connection: info
      

#  datasource:
#    hikari:
#      primary: 
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        jdbc-url: jdbc:mysql://localhost:3307/item_db?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
#        username: root
#        password: root
#      secondary: 
#        driver-class-name: oracle.jdbc.driver.OracleDriver
#        jdbc-url: jdbc:oracle:thin:@localhost:1521/xe
#        username: system
#        password: root